commerce_price.commerce_currency.*:
  type: config_entity
  label: 'Currency'
  mapping:
    currency_code:
      type: string
      label: 'Currency code'
    name:
      type: label
      label: 'Name'
      translatable: true
    numericCode:
      type: integer
      label: 'Numeric code'
    symbol:
      type: string
      label: 'Symbol'
      translatable: true
    fractionDigits:
      type: integer
      label: 'Fraction digits'
    status:
      label: Status
      type: boolean
