commerce_price.commerce_currency.*:
  type: config_entity
  label: 'Currency'
  mapping:
    currencyCode:
      type: string
      label: 'Currency code'
    name:
      type: label
      label: 'Name'
      translatable: true
    numericCode:
      type: integer
      label: 'Numeric code'
    symbol:
      type: string
      label: 'Symbol'
      translatable: true
    fractionDigits:
      type: integer
      label: 'Fraction digits'
    status:
      label: Status
      type: boolean

field.formatter.settings.price_default:
  type: mapping
  label: 'Default price formatter settings'
  mapping:
    strip_trailing_zeroes:
      type: boolean
      label: 'Strip trailing zeroes after the decimal point'
    display_currency_code:
      type: boolean
      label: 'Display the currency code instead of the currency symbol'
