commerce_price.commerce_currency.*:
  type: config_entity
  label: 'Currency'
  mapping:
    currencyCode:
      type: string
      label: 'Currency code'
    name:
      type: label
      label: 'Name'
      translatable: true
    numericCode:
      type: integer
      label: 'Numeric code'
    symbol:
      type: string
      label: 'Symbol'
      translatable: true
    fractionDigits:
      type: integer
      label: 'Fraction digits'
    status:
      label: Status
      type: boolean

commerce_price.commerce_number_format.*:
  type: config_entity
  label: 'Number Format'
  mapping:
    locale:
      type: string
      label: 'Locale'
    name:
      type: label
      label: 'Name'
      translatable: true
    numberingSystem:
      type: string
      label: 'Numbering System'
    decimalSeparator:
      type: string
      label: 'Decimal Separator'
    plusSign:
      type: string
      label: 'Plus sign'
    minusSign:
      type: string
      label: 'Minus sign'
    percentSign:
      type: string
      label: 'Percent sign'
    decimalPattern:
      type: string
      label: 'Decimal pattern'
    percentPattern:
      type: string
      label: 'Percent pattern'
    currencyPattern:
      type: string
      label: 'Currency pattern'
    accountingCurrencyPattern:
      type: string
      label: 'Accounting currency pattern'
    groupingSeparator:
      type: string
      label: 'Grouping Separator'
    status:
      label: Status
      type: boolean
