commerce_line_item.commerce_line_item_type.*:
  type: config_entity
  label: 'Line item type'
  mapping:
    label:
      type: label
      label: 'Label'
    id:
      type: string
      label: 'Machine-readable name'
    description:
      type: text
      label: 'Description'
