field.value.commerce_remote_id:
 type: mapping
 label: 'Default value'
 mapping:
   provider:
     type: string
     label: 'Provider'
   remote_id:
     type: string
     label: 'Remote ID'

field.widget.settings.commerce_entity_select:
  type: mapping
  label: 'Entity select widget settings'
  mapping:
    autocomplete_threshold:
      type: integer
      label: 'Autocomplete threshold'
    autocomplete_size:
      type: integer
      label: 'Autocomplete size'
    autocomplete_placeholder:
      type: string
      label: 'Autocomplete placeholder'

field.field_settings.commerce_plugin_item:*:
  type: mapping
  label: 'Plugin item field settings'
  mapping:
    categories:
      type: sequence
      label: 'Categories'
      sequence:
        - type: string

field.widget.settings.commerce_auto_sku:
  type: mapping
  label: 'Commerce auto SKU format settings'
  mapping:
    iniqid_enabled:
      type: boolean
      label: 'Enable unique auto SKU values generation'
    more_entropy:
      type: boolean
      label: 'More unique'
    prefix:
      type: string
      label: 'SKU prefix'
    suffix:
      type: string
      label: 'SKU suffix'
    size:
      type: integer
      label: 'Size of textfield'
    placeholder:
      type: label
      label: 'Placeholder'

views.argument_validator.commerce_current_user:
  type: mapping
  label: 'Current user'
  mapping:
    admin_permission:
      type: string
      label: 'Admin permission'

views.field.commerce_entity_bundle:
  type: views.field.field
  mapping:
    hide_single_bundle:
      type: boolean
      label: 'Hide if there''s only one bundle.'

views.filter.commerce_entity_bundle:
  type: views.filter.in_operator
  label: 'Bundle'
  mapping:
    expose:
      type: mapping
      label: 'Expose'
      mapping:
        reduce:
          type: boolean
          label: 'Reduce'
        hide_single_bundle:
          type: boolean
          label: 'Hide if there''s only one bundle.'
