commerce_product.commerce_product_type.*:
  type: config_entity
  label: 'Product type'
  mapping:
    id:
      type: string
      label: 'Type'
    label:
        type: label
        label: 'Label'
    revision:
      type: integer
      label: 'Create new revision'
    digital:
      type: integer
      label: 'Products of this type represent digital services.'
    description:
      type: text
      label: 'Description'

field.field.*.*.*.third_party.commerce_product:
  type: mapping
  label: 'Product attributes'
  mapping:
    attribute_field:
        type: boolean
        label: 'Whether or not this field should be used as a product attribute'
    attribute_widget:
        type: string
        label: 'The widget to use for the product attribute'
    attribute_widget_title:
        type: string
        label: 'The title of the product attribute for the Add to Cart form'
        translatable: true
